name: flutter_piano
description: A Crossplatform Midi Piano built with Flutter.
author: Rody Davis Jr <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/flutter_piano
version: 1.0.4+48

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tonic: ^0.2.3
  cupertino_icons: ^0.1.2
  vibrate: ^0.0.4
  flutter_midi: ^1.0.0
  app_review: ^1.0.0
  intl: ^0.16.0
  font_awesome_flutter: ^8.4.0
  url_launcher: ^5.1.4
  universal_html: ^1.1.6
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  firebase_analytics: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  screenshots: ^0.1.7
  intl_translation: ^0.17.2

dependency_overrides:
  localstorage:
    git: https://github.com/AppleEducate/flutter_localstorage

flutter:
  uses-material-design: true

  assets:
   - assets/sounds/Piano.sf2
